os: osx
language: objective-c
osx_image: xcode10.1
sudo: false
name: Theos Build
env:
  global:
    - THEOS=~/theos

before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "ConorTheDev"
    - git config --local user.email "con0r.b@protonmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG

before_install:
  - export CIBUILD=1
  - brew install ldid
  - git clone --recursive git://github.com/theos/theos.git ~/theos
  - curl -LO https://github.com/xybp888/iOS-SDKs/archive/master.zip
  - unzip -qq master.zip -d $THEOS/sdks

jobs:
  include:
    - script: make package FINALPACKAGE=1
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "./packages/me.conorthedev.lockwidgets_1.0.1_iphoneos-arm.deb"
        skip_cleanup: true
        prerelease: true
        on:
          tags: true
